# Site settings
title: KyuDevelop
email: lee@kyuhyuk.kr
description: KyuHyuk Lee Blog
baseurl: ""
url: "http://kyuhyuk.kr"
facebook_username: LeeKyuHyuk
twitter_username: LeeKyuHyuk
github_username:  LeeKyuHyuk
generator:  KyuHyuk Lee

# Build settings
markdown: kramdown

# Plugins
gems:
  - jemoji
  - jekyll-sitemap
